name: Sync LeetCode Solutions

permissions:
  contents: write   # Required to push commits from the workflow

on:
  schedule:
    - cron: '0 1 * * *'  # Daily at 01:00 UTC
  workflow_dispatch:

jobs:
  update-leetcode:
    runs-on: ubuntu-latest

    env:
      LEETCODE_USERNAME: Psy_Consumer

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requests
      run: pip install requests

    - name: Run fetch_leetcode.py
      run: python fetch_leetcode.py

    - name: Commit & Push changes (only if new code files were added)
      run: |
        git config --global user.email "sidtyagiid@gmail.com"
        git config --global user.name  "Siddhant"
        git add -A
        if git diff --cached --quiet; then
          echo "No new changes to commit."
        else
          git commit -m "Update LeetCode solutions $(date '+%Y-%m-%d %H:%M')"
          git push
        fi

